-- USM Chapter seed: California SSAs (from outreach tracker)
-- Each row creates a live landing page at /ssas/<slug>
insert into public.ssas (slug, name, school, city, state, instagram_handle, status) values
  ('fresno-gurbani', 'Fresno Gurbani Club', 'CSU Fresno', 'Fresno', 'CA', 'fresnostate_gurbani_club', 'live'),
  ('fresno-state', 'Fresno State SSA', 'CSU Fresno', 'Fresno', 'CA', 'fresnostate_ssa', 'live'),
  ('sacstate', 'SSA Sac State', 'CSU Sac State', 'Sacramento', 'CA', 'ssasacstate', 'live'),
  ('stanstate', 'SSA Stan State', 'CSU Stanislaus', 'Turlock', 'CA', 'stanstatessa', 'live'),
  ('ucdavis', 'UCD SSA', 'UC Davis', 'Davis', 'CA', 'ssaucd', 'live'),
  ('ucmerced', 'SSA UCM', 'UC Merced', 'Merced', 'CA', 'ssaucm', 'live'),
  ('uop', 'UOP SSA', 'University of Pacific', 'Stockton', 'CA', 'ssa_uop', 'live'),
  ('csueastbay', 'SSAEB', 'CSU East Bay', 'Hayward', 'CA', 'ssa.eastbay', 'live'),
  ('ohlone', 'SSA Ohlone', 'Ohlone College', 'Fremont', 'CA', 'ssaohlone', 'live'),
  ('stanford', 'Stanford University SSA', 'Leland Stanford Junior University', 'Stanford', 'CA', 'stanfordsikhs', 'live'),
  ('sfsu', 'SFSU SSA', 'San Francisco State University', 'San Francisco', 'CA', 'sfsu_ssa', 'live'),
  ('sjsu', 'SJSU SSA', 'San Jose State University', 'San Jose', 'CA', 'ssasjsu', 'live'),
  ('santaclara', 'Sikhs of Santa Clara', 'Santa Clara University', 'Santa Clara', 'CA', 'scusikhs', 'live'),
  ('berkeley', 'UCBSSA', 'UC Berkeley', 'Berkeley', 'CA', 'ucbssa', 'live'),
  ('ucsc', 'SSA UC Santa Cruz', 'UC Santa Cruz', 'Santa Cruz', 'CA', 'ucsc_ssa', 'live'),
  ('usf', 'SSA USFCA', 'University of San Francisco', 'San Francisco', 'CA', 'ssa.usfca', 'live'),
  ('calpolypomona', 'CPP Sikh Student Association', 'Cal Poly Pomona', 'Pomona', 'CA', 'cppssa', 'live'),
  ('calpolyslo', 'Cal Poly SSA', 'Cal Poly SLO', 'San Luis Obispo', 'CA', 'calpolyssa', 'live'),
  ('csufullerton', 'SSA CSUF', 'CSU Fullerton', 'Fullerton', 'CA', 'csufssa', 'live'),
  ('csulb', 'CSULB SSA', 'CSU Long Beach', 'Long Beach', 'CA', 'ssa_csulb', 'live'),
  ('csun', 'CSUN SSA', 'CSU Northridge', 'Los Angeles', 'CA', 'csun_ssa', 'live'),
  ('csusb', 'CSUSB SSA', 'CSU San Bernardino', 'San Bernardino', 'CA', 'csusbssa', 'live'),
  ('occ', 'SSA at OCC', 'Orange Coast College', 'Costa Mesa', 'CA', 'ssa.occ', 'live'),
  ('uci', 'SSA UCI', 'UC Irvine', 'Irvine', 'CA', 'ssa.ucirvine', 'live'),
  ('ucla', 'SSA UCLA', 'UC Los Angeles', 'Los Angeles', 'CA', 'ucla_ssa', 'live'),
  ('ucr', 'Sikh Student Association at UCR', 'UC Riverside', 'Riverside', 'CA', 'ssa_ucr', 'live'),
  ('ucsd', 'UCSD SSA', 'UC San Diego', 'La Jolla', 'CA', 'ssa_ucsd', 'live'),
  ('ucsb', 'UCSB SSA', 'UC Santa Barbara', 'Santa Barbara', 'CA', 'ucsbssa', 'live'),
  ('usc', 'USC SSA', 'University of Southern California', 'Los Angeles', 'CA', 'uscsikhs', 'live'),
  ('sdsu', 'SDSU SSA', 'San Diego State University', 'San Diego', 'CA', 'sdsu_ssa', 'live')
on conflict (slug) do nothing;
